version: "3.7"

services:
  server:
    image: klutchell/unbound:1.25.1@sha256:4718d579152d49a3eaf7cbc1ce67f4e2e0d6f396be8f604a2416a94e7a250be8
    restart: on-failure
    ports:
      - "5335:5335/tcp"
      - "5335:5335/udp"
    volumes:
      - ./data/unbound/custom.conf.d:/etc/unbound/custom.conf.d:ro
    healthcheck:
      test: ["CMD", "drill-hc", "@127.0.0.1", "-p", "5335", "cloudflare.com"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
