version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: wio-unbound-pihole_web_1
      APP_PORT: 8054

  web:
    image: pihole/pihole:2026.05.0@sha256:70a9c11171ded2eee735d88c127996da209284a329d50f5ae59c06b861d401b3
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - default
    volumes:
      - ${APP_DATA_DIR}/data/pihole:/etc/pihole
      - ${APP_DATA_DIR}/data/dnsmasq:/etc/dnsmasq.d
    environment:
      FTLCONF_dns_upstreams: "unbound#5335"
      FTLCONF_webserver_api_password: "${APP_PASSWORD}"
      FTLCONF_webserver_port: "8054,[::]:8054"
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_dns_dnssec: "false"
    depends_on:
      unbound:
        condition: service_healthy
    cap_add:
      - NET_ADMIN

  unbound:
    image: klutchell/unbound:1.25.1@sha256:26bcae217bfd477625db0de7db414fce79f880de20fff72b2c4b1f2af8d6c616
    restart: on-failure
    networks:
      - default
    volumes:
      - ${APP_DATA_DIR}/data/unbound/custom.conf.d:/etc/unbound/custom.conf.d:ro
    healthcheck:
      test: ["CMD", "drill-hc", "@127.0.0.1", "-p", "5335", "cloudflare.com"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    driver: bridge
